
CREATE TABLE Hazi (
    LOGIN NVARCHAR(255) MASKED WITH (FUNCTION = 'partial(1,"***",1)') NOT NULL,
    EMAIL NVARCHAR(255) MASKED WITH (FUNCTION = 'email()') NOT NULL,
    NEV NVARCHAR(255) MASKED WITH (FUNCTION = 'partial(1,"***",1)') NOT NULL, 
    SZULEV INT MASKED WITH (FUNCTION = 'random(1900,2024)') NULL, 
    NEM NVARCHAR(1) NULL,
    CIM NVARCHAR(255) NULL,
    PRIMARY KEY (LOGIN)
);
GO

INSERT INTO Hazi (LOGIN, EMAIL, NEV, SZULEV, NEM, CIM)
SELECT DISTINCT LOGIN, EMAIL, NEV, SZULEV, NEM, CIM
FROM Ugyfel;
GO

CREATE USER MaskUser WITHOUT LOGIN;
GO

GRANT SELECT ON Hazi TO MaskUser;
GO

CREATE VIEW Hazi_Masked AS
SELECT LOGIN, EMAIL, NEV, SZULEV, NEM, CIM
FROM Hazi;
GO

GRANT SELECT ON Hazi_Masked TO MaskUser;
GO

EXECUTE AS USER = 'MaskUser';
SELECT * FROM Hazi;
SELECT * FROM Hazi_Masked;
REVERT;
GO

